theme: "minima"

title: "Lolitalim's Blog"
author: "Lolitalim"


timezone: Etc/UTC
future: false

description: "Just another ignorant homo sapien." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

# Email / Social media user names used by the minima theme:
email: "linmansheni@gmail.com"
#twitter_username: "twitteruser"
github_username: "Lolitalim"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

rss: rss

show_excerpts: false

# plugin: jekyll-titles-from-headings
titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - archive.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics:
  - UA-185058308-1 # Old GA Universal Analytics property
  - G-RY6FRPMXHZ # New GA4 property

gravatar_hash: 2136e716a089f4a3794f4007328c7bfb
code_block_max_height: 500px

home_post_limit: 5


defaults:
  - scope:
      path: ""
    values:
      image: /docs/assets/img/me/me.jpeg # Apply default site image
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true